# Generated by Django 6.1.1 on 2026-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
